In [2]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [3]:
df = pd.read_csv("iris.csv")
X = df.iloc[:, 0:4].values

In [4]:
y = df.iloc[:,4].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)



In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [8]:
lda = LinearDiscriminantAnalysis(n_components=1)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(max_depth=2,random_state=0)
classifier.fit(X_train_lda,y_train)
y_pred= classifier.predict(X_test_lda)

In [9]:
conf_matrix = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy:",accuracy)

Confusion Matrix:
 [[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
Accuracy: 1.0
